import type { ComponentDef, ComponentType } from "./types";

const componentDefs: Record<ComponentType, ComponentDef> = {
  // ─── Passive Components ───
  led: {
    type: "led",
    label: "LED",
    category: "output",
    width: 40,
    height: 50,
    pins: [
      {
        id: "anode",
        label: "正极 (+)",
        type: "digital",
        side: "top",
        offset: 0.5,
      },
      {
        id: "cathode",
        label: "负极 (-)",
        type: "ground",
        side: "bottom",
        offset: 0.5,
      },
    ],
    defaultProps: { color: "#ff3333", forwardVoltage: 2.0, maxCurrent: 20 },
  },
  resistor: {
    type: "resistor",
    label: "电阻",
    category: "passive",
    width: 60,
    height: 24,
    pins: [
      { id: "pin1", label: "引脚1", type: "analog", side: "left", offset: 0.5 },
      {
        id: "pin2",
        label: "引脚2",
        type: "analog",
        side: "right",
        offset: 0.5,
      },
    ],
    defaultProps: { resistance: 220, unit: "Ω" },
  },
  capacitor: {
    type: "capacitor",
    label: "电容",
    category: "passive",
    width: 30,
    height: 40,
    pins: [
      {
        id: "positive",
        label: "正极",
        type: "analog",
        side: "top",
        offset: 0.5,
      },
      {
        id: "negative",
        label: "负极",
        type: "analog",
        side: "bottom",
        offset: 0.5,
      },
    ],
    defaultProps: { capacitance: 100, unit: "μF", maxVoltage: 16 },
  },
  potentiometer: {
    type: "potentiometer",
    label: "电位器",
    category: "passive",
    width: 50,
    height: 50,
    pins: [
      { id: "pin1", label: "引脚1", type: "analog", side: "left", offset: 0.3 },
      {
        id: "wiper",
        label: "滑动端",
        type: "analog",
        side: "right",
        offset: 0.5,
      },
      { id: "pin2", label: "引脚2", type: "analog", side: "left", offset: 0.7 },
    ],
    defaultProps: { resistance: 10000, position: 50 },
  },

  // ─── Active Components ───
  button: {
    type: "button",
    label: "按钮",
    category: "active",
    width: 40,
    height: 40,
    pins: [
      {
        id: "pin1",
        label: "引脚1",
        type: "digital",
        side: "left",
        offset: 0.5,
      },
      {
        id: "pin2",
        label: "引脚2",
        type: "digital",
        side: "right",
        offset: 0.5,
      },
    ],
    defaultProps: { momentary: true, pressed: false },
  },
  switch: {
    type: "switch",
    label: "开关",
    category: "active",
    width: 50,
    height: 30,
    pins: [
      {
        id: "pin1",
        label: "引脚1",
        type: "digital",
        side: "left",
        offset: 0.5,
      },
      {
        id: "pin2",
        label: "引脚2",
        type: "digital",
        side: "right",
        offset: 0.5,
      },
    ],
    defaultProps: { on: false },
  },

  // ─── Output Components ───
  motor: {
    type: "motor",
    label: "直流电机",
    category: "output",
    width: 50,
    height: 50,
    pins: [
      {
        id: "positive",
        label: "正极",
        type: "digital",
        side: "left",
        offset: 0.4,
      },
      {
        id: "negative",
        label: "负极",
        type: "ground",
        side: "left",
        offset: 0.6,
      },
    ],
    defaultProps: { speed: 0, maxRPM: 300 },
  },
  buzzer: {
    type: "buzzer",
    label: "蜂鸣器",
    category: "output",
    width: 40,
    height: 40,
    pins: [
      {
        id: "positive",
        label: "正极",
        type: "digital",
        side: "top",
        offset: 0.5,
      },
      {
        id: "negative",
        label: "负极",
        type: "ground",
        side: "bottom",
        offset: 0.5,
      },
    ],
    defaultProps: { frequency: 1000, active: false },
  },
  servo: {
    type: "servo",
    label: "舵机",
    category: "output",
    width: 50,
    height: 50,
    pins: [
      { id: "signal", label: "信号", type: "pwm", side: "top", offset: 0.3 },
      { id: "vcc", label: "VCC", type: "power", side: "top", offset: 0.7 },
      { id: "gnd", label: "GND", type: "ground", side: "bottom", offset: 0.5 },
    ],
    defaultProps: { angle: 90, minAngle: 0, maxAngle: 180 },
  },
  seven_segment: {
    type: "seven_segment",
    label: "七段数码管",
    category: "output",
    width: 50,
    height: 70,
    pins: [
      { id: "a", label: "a", type: "digital", side: "top", offset: 0.2 },
      { id: "b", label: "b", type: "digital", side: "top", offset: 0.4 },
      { id: "c", label: "c", type: "digital", side: "top", offset: 0.6 },
      { id: "d", label: "d", type: "digital", side: "top", offset: 0.8 },
      { id: "e", label: "e", type: "digital", side: "bottom", offset: 0.2 },
      { id: "f", label: "f", type: "digital", side: "bottom", offset: 0.4 },
      { id: "g", label: "g", type: "digital", side: "bottom", offset: 0.6 },
      { id: "dp", label: "dp", type: "digital", side: "bottom", offset: 0.8 },
      { id: "com", label: "COM", type: "ground", side: "left", offset: 0.5 },
    ],
    defaultProps: { type: "common_cathode", digit: -1 },
  },
  lcd: {
    type: "lcd",
    label: "LCD 1602",
    category: "output",
    width: 80,
    height: 50,
    pins: [
      { id: "vss", label: "VSS", type: "ground", side: "left", offset: 0.1 },
      { id: "vdd", label: "VDD", type: "power", side: "left", offset: 0.2 },
      { id: "v0", label: "V0", type: "analog", side: "left", offset: 0.3 },
      { id: "rs", label: "RS", type: "digital", side: "left", offset: 0.4 },
      { id: "rw", label: "RW", type: "digital", side: "left", offset: 0.5 },
      { id: "en", label: "EN", type: "digital", side: "left", offset: 0.6 },
      { id: "d4", label: "D4", type: "digital", side: "right", offset: 0.2 },
      { id: "d5", label: "D5", type: "digital", side: "right", offset: 0.3 },
      { id: "d6", label: "D6", type: "digital", side: "right", offset: 0.4 },
      { id: "d7", label: "D7", type: "digital", side: "right", offset: 0.5 },
      { id: "bl_a", label: "背光+", type: "power", side: "right", offset: 0.8 },
      {
        id: "bl_k",
        label: "背光-",
        type: "ground",
        side: "right",
        offset: 0.9,
      },
    ],
    defaultProps: { text: "", rows: 2, cols: 16 },
  },

  // ─── Sensor Components ───
  photoresistor: {
    type: "photoresistor",
    label: "光敏电阻",
    category: "sensor",
    width: 40,
    height: 40,
    pins: [
      { id: "pin1", label: "引脚1", type: "analog", side: "left", offset: 0.5 },
      {
        id: "pin2",
        label: "引脚2",
        type: "analog",
        side: "right",
        offset: 0.5,
      },
    ],
    defaultProps: { resistance: 10000, lightLevel: 50 },
  },
  thermistor: {
    type: "thermistor",
    label: "热敏电阻",
    category: "sensor",
    width: 40,
    height: 40,
    pins: [
      { id: "pin1", label: "引脚1", type: "analog", side: "left", offset: 0.5 },
      {
        id: "pin2",
        label: "引脚2",
        type: "analog",
        side: "right",
        offset: 0.5,
      },
    ],
    defaultProps: { resistance: 10000, temperature: 25 },
  },
  ultrasonic: {
    type: "ultrasonic",
    label: "超声波传感器",
    category: "sensor",
    width: 60,
    height: 50,
    pins: [
      { id: "vcc", label: "VCC", type: "power", side: "left", offset: 0.2 },
      { id: "trig", label: "Trig", type: "digital", side: "left", offset: 0.4 },
      { id: "echo", label: "Echo", type: "digital", side: "left", offset: 0.6 },
      { id: "gnd", label: "GND", type: "ground", side: "left", offset: 0.8 },
    ],
    defaultProps: { distance: 0, maxRange: 400 },
  },

  // ─── MCU Components ───
  arduino_uno: {
    type: "arduino_uno",
    label: "Arduino UNO",
    category: "mcu",
    width: 120,
    height: 160,
    pins: [
      // Digital pins
      { id: "D0", label: "D0", type: "digital", side: "top", offset: 0.08 },
      { id: "D1", label: "D1", type: "digital", side: "top", offset: 0.14 },
      { id: "D2", label: "D2", type: "digital", side: "top", offset: 0.2 },
      { id: "D3", label: "D3", type: "pwm", side: "top", offset: 0.26 },
      { id: "D4", label: "D4", type: "digital", side: "top", offset: 0.32 },
      { id: "D5", label: "D5", type: "pwm", side: "top", offset: 0.38 },
      { id: "D6", label: "D6", type: "pwm", side: "top", offset: 0.44 },
      { id: "D7", label: "D7", type: "digital", side: "top", offset: 0.5 },
      { id: "D8", label: "D8", type: "digital", side: "top", offset: 0.56 },
      { id: "D9", label: "D9", type: "pwm", side: "top", offset: 0.62 },
      { id: "D10", label: "D10", type: "pwm", side: "top", offset: 0.68 },
      { id: "D11", label: "D11", type: "pwm", side: "top", offset: 0.74 },
      { id: "D12", label: "D12", type: "digital", side: "top", offset: 0.8 },
      { id: "D13", label: "D13", type: "digital", side: "top", offset: 0.86 },
      // Analog pins
      { id: "A0", label: "A0", type: "analog", side: "bottom", offset: 0.15 },
      { id: "A1", label: "A1", type: "analog", side: "bottom", offset: 0.25 },
      { id: "A2", label: "A2", type: "analog", side: "bottom", offset: 0.35 },
      { id: "A3", label: "A3", type: "analog", side: "bottom", offset: 0.45 },
      { id: "A4", label: "A4", type: "analog", side: "bottom", offset: 0.55 },
      { id: "A5", label: "A5", type: "analog", side: "bottom", offset: 0.65 },
      // Power
      { id: "5V", label: "5V", type: "power", side: "right", offset: 0.15 },
      { id: "3V3", label: "3.3V", type: "power", side: "right", offset: 0.25 },
      { id: "GND1", label: "GND", type: "ground", side: "right", offset: 0.35 },
      { id: "GND2", label: "GND", type: "ground", side: "right", offset: 0.45 },
      { id: "VIN", label: "VIN", type: "power", side: "right", offset: 0.55 },
    ],
    defaultProps: { board: "uno" },
  },
  esp32: {
    type: "esp32",
    label: "ESP32",
    category: "mcu",
    width: 100,
    height: 140,
    pins: [
      { id: "GPIO0", label: "GPIO0", type: "io", side: "top", offset: 0.1 },
      { id: "GPIO1", label: "GPIO1", type: "io", side: "top", offset: 0.2 },
      { id: "GPIO2", label: "GPIO2", type: "io", side: "top", offset: 0.3 },
      { id: "GPIO3", label: "GPIO3", type: "io", side: "top", offset: 0.4 },
      { id: "GPIO4", label: "GPIO4", type: "io", side: "top", offset: 0.5 },
      { id: "GPIO5", label: "GPIO5", type: "io", side: "top", offset: 0.6 },
      { id: "GPIO12", label: "GPIO12", type: "io", side: "top", offset: 0.7 },
      { id: "GPIO13", label: "GPIO13", type: "io", side: "top", offset: 0.8 },
      { id: "GPIO14", label: "GPIO14", type: "io", side: "top", offset: 0.9 },
      {
        id: "ADC0",
        label: "ADC0",
        type: "analog",
        side: "bottom",
        offset: 0.2,
      },
      {
        id: "ADC1",
        label: "ADC1",
        type: "analog",
        side: "bottom",
        offset: 0.35,
      },
      {
        id: "ADC2",
        label: "ADC2",
        type: "analog",
        side: "bottom",
        offset: 0.5,
      },
      {
        id: "ADC3",
        label: "ADC3",
        type: "analog",
        side: "bottom",
        offset: 0.65,
      },
      { id: "3V3", label: "3.3V", type: "power", side: "right", offset: 0.15 },
      { id: "GND", label: "GND", type: "ground", side: "right", offset: 0.3 },
      { id: "VIN", label: "VIN", type: "power", side: "right", offset: 0.45 },
    ],
    defaultProps: { board: "esp32" },
  },
  stm32: {
    type: "stm32",
    label: "STM32F103",
    category: "mcu",
    width: 140,
    height: 200,
    pins: [
      // Port A — left side
      { id: "PA0", label: "PA0", type: "io", side: "left", offset: 0.06 },
      { id: "PA1", label: "PA1", type: "io", side: "left", offset: 0.1 },
      { id: "PA2", label: "PA2", type: "io", side: "left", offset: 0.14 },
      { id: "PA3", label: "PA3", type: "io", side: "left", offset: 0.18 },
      { id: "PA4", label: "PA4", type: "io", side: "left", offset: 0.22 },
      { id: "PA5", label: "PA5", type: "io", side: "left", offset: 0.26 },
      { id: "PA6", label: "PA6", type: "io", side: "left", offset: 0.3 },
      { id: "PA7", label: "PA7", type: "io", side: "left", offset: 0.34 },
      { id: "PA8", label: "PA8", type: "io", side: "left", offset: 0.38 },
      { id: "PA9", label: "PA9", type: "io", side: "left", offset: 0.42 },
      { id: "PA10", label: "PA10", type: "io", side: "left", offset: 0.46 },
      { id: "PA11", label: "PA11", type: "io", side: "left", offset: 0.5 },
      { id: "PA12", label: "PA12", type: "io", side: "left", offset: 0.54 },
      { id: "PA13", label: "PA13", type: "io", side: "left", offset: 0.58 },
      { id: "PA14", label: "PA14", type: "io", side: "left", offset: 0.62 },
      { id: "PA15", label: "PA15", type: "io", side: "left", offset: 0.66 },
      // Port B — right side
      { id: "PB0", label: "PB0", type: "io", side: "right", offset: 0.06 },
      { id: "PB1", label: "PB1", type: "io", side: "right", offset: 0.1 },
      { id: "PB3", label: "PB3", type: "io", side: "right", offset: 0.14 },
      { id: "PB4", label: "PB4", type: "io", side: "right", offset: 0.18 },
      { id: "PB5", label: "PB5", type: "io", side: "right", offset: 0.22 },
      { id: "PB6", label: "PB6", type: "io", side: "right", offset: 0.26 },
      { id: "PB7", label: "PB7", type: "io", side: "right", offset: 0.3 },
      { id: "PB8", label: "PB8", type: "io", side: "right", offset: 0.34 },
      { id: "PB9", label: "PB9", type: "io", side: "right", offset: 0.38 },
      { id: "PB10", label: "PB10", type: "io", side: "right", offset: 0.42 },
      { id: "PB11", label: "PB11", type: "io", side: "right", offset: 0.46 },
      { id: "PB12", label: "PB12", type: "io", side: "right", offset: 0.5 },
      { id: "PB13", label: "PB13", type: "io", side: "right", offset: 0.54 },
      { id: "PB14", label: "PB14", type: "io", side: "right", offset: 0.58 },
      { id: "PB15", label: "PB15", type: "io", side: "right", offset: 0.62 },
      // Port C — bottom
      { id: "PC13", label: "PC13", type: "io", side: "bottom", offset: 0.3 },
      { id: "PC14", label: "PC14", type: "io", side: "bottom", offset: 0.5 },
      { id: "PC15", label: "PC15", type: "io", side: "bottom", offset: 0.7 },
      // Power — top
      { id: "V3_3", label: "3.3V", type: "power", side: "top", offset: 0.15 },
      { id: "V5", label: "5V", type: "power", side: "top", offset: 0.35 },
      { id: "GND1", label: "GND", type: "ground", side: "top", offset: 0.55 },
      { id: "GND2", label: "GND", type: "ground", side: "top", offset: 0.75 },
      { id: "VBAT", label: "VBAT", type: "power", side: "top", offset: 0.9 },
    ],
    defaultProps: { board: "stm32f103c8t6", clock: 72 },
  },
  stm32_bluepill: {
    type: "stm32_bluepill",
    label: "Blue Pill 开发板",
    category: "mcu",
    width: 120,
    height: 180,
    pins: [
      // Left column (top to bottom)
      { id: "PB9", label: "PB9", type: "io", side: "left", offset: 0.05 },
      { id: "PB8", label: "PB8", type: "io", side: "left", offset: 0.1 },
      { id: "PB7", label: "PB7", type: "io", side: "left", offset: 0.15 },
      { id: "PB6", label: "PB6", type: "io", side: "left", offset: 0.2 },
      { id: "PB5", label: "PB5", type: "io", side: "left", offset: 0.25 },
      { id: "PB4", label: "PB4", type: "io", side: "left", offset: 0.3 },
      { id: "PB3", label: "PB3", type: "io", side: "left", offset: 0.35 },
      { id: "PA15", label: "PA15", type: "io", side: "left", offset: 0.4 },
      { id: "PA12", label: "PA12", type: "io", side: "left", offset: 0.45 },
      { id: "PA11", label: "PA11", type: "io", side: "left", offset: 0.5 },
      { id: "PA10", label: "PA10", type: "io", side: "left", offset: 0.55 },
      { id: "PA9", label: "PA9", type: "io", side: "left", offset: 0.6 },
      { id: "PA8", label: "PA8", type: "io", side: "left", offset: 0.65 },
      { id: "PB15", label: "PB15", type: "io", side: "left", offset: 0.7 },
      { id: "PB14", label: "PB14", type: "io", side: "left", offset: 0.75 },
      { id: "PB13", label: "PB13", type: "io", side: "left", offset: 0.8 },
      { id: "PB12", label: "PB12", type: "io", side: "left", offset: 0.85 },
      // Right column (top to bottom)
      { id: "PC13", label: "PC13", type: "io", side: "right", offset: 0.05 },
      { id: "VBAT", label: "VBAT", type: "power", side: "right", offset: 0.1 },
      { id: "PC14", label: "PC14", type: "io", side: "right", offset: 0.15 },
      { id: "PC15", label: "PC15", type: "io", side: "right", offset: 0.2 },
      { id: "PA0", label: "PA0", type: "io", side: "right", offset: 0.28 },
      { id: "PA1", label: "PA1", type: "io", side: "right", offset: 0.33 },
      { id: "PA2", label: "PA2", type: "io", side: "right", offset: 0.38 },
      { id: "PA3", label: "PA3", type: "io", side: "right", offset: 0.43 },
      { id: "PA4", label: "PA4", type: "io", side: "right", offset: 0.48 },
      { id: "PA5", label: "PA5", type: "io", side: "right", offset: 0.53 },
      { id: "PA6", label: "PA6", type: "io", side: "right", offset: 0.58 },
      { id: "PA7", label: "PA7", type: "io", side: "right", offset: 0.63 },
      { id: "PB0", label: "PB0", type: "io", side: "right", offset: 0.68 },
      { id: "PB1", label: "PB1", type: "io", side: "right", offset: 0.73 },
      { id: "PB10", label: "PB10", type: "io", side: "right", offset: 0.78 },
      { id: "PB11", label: "PB11", type: "io", side: "right", offset: 0.83 },
      // Power pins — top
      { id: "3V3", label: "3.3V", type: "power", side: "top", offset: 0.25 },
      { id: "GND1", label: "GND", type: "ground", side: "top", offset: 0.5 },
      { id: "5V", label: "5V", type: "power", side: "top", offset: 0.75 },
      // Boot pins — bottom
      {
        id: "BOOT0",
        label: "BOOT0",
        type: "digital",
        side: "bottom",
        offset: 0.3,
      },
      {
        id: "BOOT1",
        label: "BOOT1",
        type: "digital",
        side: "bottom",
        offset: 0.5,
      },
      {
        id: "NRST",
        label: "NRST",
        type: "digital",
        side: "bottom",
        offset: 0.7,
      },
    ],
    defaultProps: { board: "stm32f103c8t6", clock: 72 },
  },
  oled_ssd1306: {
    type: "oled_ssd1306",
    label: "OLED (I2C)",
    category: "output",
    width: 70,
    height: 50,
    pins: [
      { id: "VCC", label: "VCC", type: "power", side: "left", offset: 0.2 },
      { id: "GND", label: "GND", type: "ground", side: "left", offset: 0.4 },
      { id: "SCL", label: "SCL", type: "digital", side: "left", offset: 0.6 },
      { id: "SDA", label: "SDA", type: "digital", side: "left", offset: 0.8 },
    ],
    defaultProps: { address: "0x3C", width: 128, height: 64, text: "" },
  },
  mpu6050: {
    type: "mpu6050",
    label: "MPU6050",
    category: "sensor",
    width: 60,
    height: 50,
    pins: [
      { id: "VCC", label: "VCC", type: "power", side: "left", offset: 0.15 },
      { id: "GND", label: "GND", type: "ground", side: "left", offset: 0.3 },
      { id: "SCL", label: "SCL", type: "digital", side: "left", offset: 0.5 },
      { id: "SDA", label: "SDA", type: "digital", side: "left", offset: 0.65 },
      { id: "INT", label: "INT", type: "digital", side: "left", offset: 0.8 },
    ],
    defaultProps: { address: "0x68", ax: 0, ay: 0, az: 0 },
  },
  stlink: {
    type: "stlink",
    label: "ST-Link V2",
    category: "connector",
    width: 60,
    height: 80,
    pins: [
      {
        id: "SWDIO",
        label: "SWDIO",
        type: "digital",
        side: "right",
        offset: 0.2,
      },
      {
        id: "SWCLK",
        label: "SWCLK",
        type: "digital",
        side: "right",
        offset: 0.35,
      },
      { id: "GND", label: "GND", type: "ground", side: "right", offset: 0.5 },
      { id: "3V3", label: "3.3V", type: "power", side: "right", offset: 0.65 },
      { id: "RST", label: "RST", type: "digital", side: "right", offset: 0.8 },
    ],
    defaultProps: {},
  },
  usb_ttl: {
    type: "usb_ttl",
    label: "USB-TTL",
    category: "connector",
    width: 60,
    height: 60,
    pins: [
      { id: "TXD", label: "TXD", type: "digital", side: "right", offset: 0.25 },
      { id: "RXD", label: "RXD", type: "digital", side: "right", offset: 0.5 },
      { id: "GND", label: "GND", type: "ground", side: "right", offset: 0.75 },
    ],
    defaultProps: {},
  },
  ir_sensor: {
    type: "ir_sensor",
    label: "红外传感器",
    category: "sensor",
    width: 50,
    height: 40,
    pins: [
      { id: "VCC", label: "VCC", type: "power", side: "left", offset: 0.25 },
      { id: "GND", label: "GND", type: "ground", side: "left", offset: 0.5 },
      { id: "OUT", label: "OUT", type: "digital", side: "left", offset: 0.75 },
    ],
    defaultProps: { detected: false },
  },
  rotary_encoder: {
    type: "rotary_encoder",
    label: "旋转编码器",
    category: "sensor",
    width: 50,
    height: 50,
    pins: [
      { id: "CLK", label: "CLK", type: "digital", side: "left", offset: 0.2 },
      { id: "DT", label: "DT", type: "digital", side: "left", offset: 0.4 },
      { id: "SW", label: "SW", type: "digital", side: "left", offset: 0.6 },
      { id: "VCC", label: "VCC", type: "power", side: "right", offset: 0.3 },
      { id: "GND", label: "GND", type: "ground", side: "right", offset: 0.6 },
    ],
    defaultProps: { position: 0, direction: "clockwise" },
  },
  w25q64: {
    type: "w25q64",
    label: "W25Q64 Flash",
    category: "output",
    width: 50,
    height: 50,
    pins: [
      { id: "CS", label: "CS", type: "digital", side: "left", offset: 0.2 },
      {
        id: "DO",
        label: "DO (MISO)",
        type: "digital",
        side: "left",
        offset: 0.4,
      },
      { id: "GND", label: "GND", type: "ground", side: "left", offset: 0.6 },
      {
        id: "DI",
        label: "DI (MOSI)",
        type: "digital",
        side: "right",
        offset: 0.2,
      },
      { id: "CLK", label: "CLK", type: "digital", side: "right", offset: 0.4 },
      { id: "VCC", label: "VCC", type: "power", side: "right", offset: 0.6 },
    ],
    defaultProps: { capacity: "8MB" },
  },

  // ─── Power & Connector ───
  battery: {
    type: "battery",
    label: "电池",
    category: "power",
    width: 40,
    height: 50,
    pins: [
      {
        id: "positive",
        label: "正极",
        type: "power",
        side: "top",
        offset: 0.5,
      },
      {
        id: "negative",
        label: "负极",
        type: "ground",
        side: "bottom",
        offset: 0.5,
      },
    ],
    defaultProps: { voltage: 9, capacity: 500 },
  },
  ground: {
    type: "ground",
    label: "GND",
    category: "power",
    width: 30,
    height: 30,
    pins: [
      { id: "gnd", label: "GND", type: "ground", side: "top", offset: 0.5 },
    ],
    defaultProps: {},
  },
  vcc: {
    type: "vcc",
    label: "VCC",
    category: "power",
    width: 30,
    height: 30,
    pins: [
      { id: "vcc", label: "VCC", type: "power", side: "bottom", offset: 0.5 },
    ],
    defaultProps: { voltage: 5 },
  },
  breadboard: {
    type: "breadboard",
    label: "面包板",
    category: "connector",
    width: 200,
    height: 100,
    pins: [],
    defaultProps: { rows: 30, cols: 10 },
  },
};

export function getComponentDef(type: ComponentType): ComponentDef {
  return componentDefs[type];
}

export function getAllComponents(): ComponentDef[] {
  return Object.values(componentDefs);
}

export function getComponentsByCategory(
  category: ComponentDef["category"],
): ComponentDef[] {
  return Object.values(componentDefs).filter((c) => c.category === category);
}

export const categoryLabels: Record<ComponentDef["category"], string> = {
  passive: "无源器件",
  active: "有源器件",
  mcu: "微控制器",
  power: "电源",
  sensor: "传感器",
  output: "输出设备",
  connector: "连接器/调试器",
};
