"""Add resource_tasks table

Revision ID: 8856cb755504
Revises: c9d93cd71293
Create Date: 2026-05-24 16:35:13.525981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8856cb755504'
down_revision: Union[str, None] = 'c9d93cd71293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_tasks',
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('resources', sa.JSON(), nullable=True),
    sa.Column('message', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_resource_tasks_task_id'), 'resource_tasks', ['task_id'], unique=False)
    op.create_index('ix_api_monitor_created_at', 'api_monitor', ['created_at'], unique=False)
    op.create_index('ix_api_monitor_endpoint', 'api_monitor', ['endpoint'], unique=False)
    op.create_index('ix_api_monitor_student_id', 'api_monitor', ['student_id'], unique=False)
    op.create_index('ix_achievements_student_achievement', 'game_achievements', ['student_id', 'achievement_id'], unique=False)
    op.create_index('ix_tasks_student_task', 'game_tasks', ['student_id', 'task_id'], unique=False)
    op.create_index(op.f('ix_knowledge_points_subject'), 'knowledge_points', ['subject'], unique=False)
    op.create_index('ix_leaderboard_period_score', 'leaderboard', ['period', 'score'], unique=False)
    op.create_index('ix_learning_records_student_action', 'learning_records', ['student_id', 'action'], unique=False)
    op.create_index('ix_llm_calls_created_at', 'llm_calls', ['created_at'], unique=False)
    op.create_index('ix_quiz_results_created_at', 'quiz_results', ['created_at'], unique=False)
    op.create_index('ix_system_health_recorded_at', 'system_health', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_system_health_recorded_at', table_name='system_health')
    op.drop_index('ix_quiz_results_created_at', table_name='quiz_results')
    op.drop_index('ix_llm_calls_created_at', table_name='llm_calls')
    op.drop_index('ix_learning_records_student_action', table_name='learning_records')
    op.drop_index('ix_leaderboard_period_score', table_name='leaderboard')
    op.drop_index(op.f('ix_knowledge_points_subject'), table_name='knowledge_points')
    op.drop_index('ix_tasks_student_task', table_name='game_tasks')
    op.drop_index('ix_achievements_student_achievement', table_name='game_achievements')
    op.drop_index('ix_api_monitor_student_id', table_name='api_monitor')
    op.drop_index('ix_api_monitor_endpoint', table_name='api_monitor')
    op.drop_index('ix_api_monitor_created_at', table_name='api_monitor')
    op.drop_index(op.f('ix_resource_tasks_task_id'), table_name='resource_tasks')
    op.drop_table('resource_tasks')
    # ### end Alembic commands ###
