"""Initial migration

Revision ID: c9d93cd71293
Revises: 
Create Date: 2026-05-24 16:32:26.253977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9d93cd71293'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_api_monitor_created_at', 'api_monitor', ['created_at'], unique=False)
    op.create_index('ix_api_monitor_endpoint', 'api_monitor', ['endpoint'], unique=False)
    op.create_index('ix_api_monitor_student_id', 'api_monitor', ['student_id'], unique=False)
    op.create_index('ix_achievements_student_achievement', 'game_achievements', ['student_id', 'achievement_id'], unique=False)
    op.create_index('ix_tasks_student_task', 'game_tasks', ['student_id', 'task_id'], unique=False)
    op.create_index(op.f('ix_knowledge_points_subject'), 'knowledge_points', ['subject'], unique=False)
    op.create_index('ix_leaderboard_period_score', 'leaderboard', ['period', 'score'], unique=False)
    op.create_index('ix_learning_records_student_action', 'learning_records', ['student_id', 'action'], unique=False)
    op.create_index('ix_llm_calls_created_at', 'llm_calls', ['created_at'], unique=False)
    op.create_index('ix_quiz_results_created_at', 'quiz_results', ['created_at'], unique=False)
    op.create_index('ix_system_health_recorded_at', 'system_health', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_system_health_recorded_at', table_name='system_health')
    op.drop_index('ix_quiz_results_created_at', table_name='quiz_results')
    op.drop_index('ix_llm_calls_created_at', table_name='llm_calls')
    op.drop_index('ix_learning_records_student_action', table_name='learning_records')
    op.drop_index('ix_leaderboard_period_score', table_name='leaderboard')
    op.drop_index(op.f('ix_knowledge_points_subject'), table_name='knowledge_points')
    op.drop_index('ix_tasks_student_task', table_name='game_tasks')
    op.drop_index('ix_achievements_student_achievement', table_name='game_achievements')
    op.drop_index('ix_api_monitor_student_id', table_name='api_monitor')
    op.drop_index('ix_api_monitor_endpoint', table_name='api_monitor')
    op.drop_index('ix_api_monitor_created_at', table_name='api_monitor')
    # ### end Alembic commands ###
