"""add onboarding_completed to student_profiles

Revision ID: 84ffd4bbb01d
Revises: 8856cb755504
Create Date: 2026-06-07 17:22:02.234166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84ffd4bbb01d'
down_revision: Union[str, None] = '8856cb755504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_favorites_created_at', 'favorites', ['created_at'], unique=False)
    op.create_index('ix_favorites_student_type', 'favorites', ['student_id', 'resource_type'], unique=False)
    op.create_index('ix_leaderboard_student_period', 'leaderboard', ['student_id', 'period'], unique=False)
    op.create_index('ix_learning_logs_student_date', 'learning_logs', ['student_id', 'date'], unique=False)
    op.create_index('ix_learning_records_student_created', 'learning_records', ['student_id', 'created_at'], unique=False)
    op.create_index('ix_llm_calls_provider', 'llm_calls', ['provider'], unique=False)
    op.create_index('ix_quiz_results_student_created', 'quiz_results', ['student_id', 'created_at'], unique=False)
    op.create_index('ix_resource_tasks_created_at', 'resource_tasks', ['created_at'], unique=False)
    op.create_index('ix_resource_tasks_status', 'resource_tasks', ['status'], unique=False)
    op.add_column('student_profiles', sa.Column('onboarding_completed', sa.Boolean(), nullable=True))
    op.create_index('ix_student_trends_student_date', 'student_trends', ['student_id', 'date'], unique=False)
    op.create_index('ix_tutor_qa_student_session', 'tutor_qa_records', ['student_id', 'session_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tutor_qa_student_session', table_name='tutor_qa_records')
    op.drop_index('ix_student_trends_student_date', table_name='student_trends')
    op.drop_column('student_profiles', 'onboarding_completed')
    op.drop_index('ix_resource_tasks_status', table_name='resource_tasks')
    op.drop_index('ix_resource_tasks_created_at', table_name='resource_tasks')
    op.drop_index('ix_quiz_results_student_created', table_name='quiz_results')
    op.drop_index('ix_llm_calls_provider', table_name='llm_calls')
    op.drop_index('ix_learning_records_student_created', table_name='learning_records')
    op.drop_index('ix_learning_logs_student_date', table_name='learning_logs')
    op.drop_index('ix_leaderboard_student_period', table_name='leaderboard')
    op.drop_index('ix_favorites_student_type', table_name='favorites')
    op.drop_index('ix_favorites_created_at', table_name='favorites')
    # ### end Alembic commands ###
